// Code generated by "stringer -type=Number"; DO NOT EDIT.

package number

import "fmt"

const _Number_name = "SingularPlural"

var _Number_index = [...]uint8{0, 8, 14}

func (i Number) String() string {
	if i < 0 || i >= Number(len(_Number_index)-1) {
		return fmt.Sprintf("Number(%d)", i)
	}
	return _Number_name[_Number_index[i]:_Number_index[i+1]]
}
